name: Unity Build Manual

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  # License
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  # Project
  UNITY_VERSION: 2022.3.62f1
  PROJECT_PATH: examples/UnitySampleGame/Sample3DGame

jobs:
  build-unity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
      - uses: game-ci/unity-builder@main
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: StandaloneLinux64

      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
